### ISSUE TITLE
Issue with lunarvim

### ISSUE THREAD

**Issue by Hermanverschooten** [brendalf/mix.nvim#2]
Hi, love this idea.

I added it to `vim.plugins` as
```
 { 'brendalf/mix.nvim',
	config = function() 
		require('mix').setup()
	end,
 }
```

When I `M:` or `:Mix` followed by a space, nothing happens.
When I press `tab` a popup appears with the possibilities, but I cannot choose one.
If I try with `:M ecto` and then `tab` the ecto part disappears.

Also the window that appears after a command is difficult to close, I need to `:q` it.

I am using NVIM v0.8.0-dev+1991-g2b1abe3c9 and lunarvim master-b04aefb.

Would you have any clues on how to resolve these?

**Comment by brendalf** [comment]
Hello @Hermanverschooten,
Thanks for raising this.
We will take a closer look later today.

**Comment by brendalf** [comment]
Hi @Hermanverschooten.
Thanks again for reporting this and sorry for the delay.
After a little investigation, @kessejones and I discovered that the need to press `tab` to see the list of options is the default for neovim and lunarvim.
The auto-completion that we have and you can see in the gif in the README of this project is actually coming from another plugin called [hrsh7th/cmp-cmdline](https://github.com/hrsh7th/cmp-cmdline).
You need to install this plugin if you want to get the same smooth experience.
I will add this information to our README to make sure that everyone knows how to do it.
